name: Auditoría de cambios en repositorio

on:
  push:
    branches:
      - main
      #- develop

jobs:
  auditoria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # trae al menos 2 commits para que HEAD~1 exista

      - name: Ejecutar auditoría
        id: audit
        run: |
          chmod +x ../scripts/auditoria_git.sh
          sh ../scripts/auditoria_git.sh
